modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "duckling"
version = "${version}"
displayName = "Duckling"
authors = "Artist - Frogipher, Dev - ThatGravyBoat"
description = """
Adds some quacky little friends!
Quacking Sounds - freesoundslibrary.com/duck-quack/
Note: Sounds were edited out and pitched up and down."""

[[dependencies.duckling]]
    modId = "forge"
    mandatory = true
    versionRange = "[41,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.duckling]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,)"
    ordering = "NONE"
    side = "BOTH"